### ISSUE TITLE
Vision Model

### ISSUE THREAD

**Issue by muhammadwaqas476074** [TheRoboticsClub/gsoc2024-ZebinHuang#1]
I just wanna ask are you going to use pretrained Vision model for your work or going to train a new one.
If so, I am curious about how are you going to deal with performance issue.

**Comment by zebin-huang** [comment]
> I just wanna ask are you going to use pretrained Vision model for your work or going to train a new one. If so, I am curious about how are you going to deal with performance issue.


Hi, We are currently developing and exploring new models, focusing primarily on LLM models rather than pure vision models. If you have any ideas or suggestions, we'd be happy to discuss them. For more details on the model, you can refer to this similar project last year's [documentation](https://theroboticsclub.github.io/gsoc2023-Meiqi_Zhao/).
